### ISSUE TITLE
Allow Development instances to run without the MailChimp API

### ISSUE THREAD

**Issue by rpowelll** [wordset/wordset-api#3]
Right now to run the Wordset API locally, a developer needs to create a Mailchimp account, set up a new list called _Wordset_, and configure a `MAILCHIMP_KEY` environment variable for the Rails app to even boot successfully. From what I can tell, the app doesn't actually appear to be using the Mailchimp API while in the development environment, so would it make sense to remove that dependency when running locally?

**Comment by malrase** [comment]
Yes, definitely! Happily take a patch for that. I know the User model uses it. We don't have a dev account setup, but it's worked for us so far... but better without it!

**Comment by hcatlin** [comment]
I'm pretty sure that I fixed it with 2db5b86a42d5da1e4d0cf14dbf70712693bbcbb1

**Comment by interestinall** [comment]
commenting out the mailchimp.rb file in wordset-api/config/initializers fixed this for me.

**Comment by rpowelll** [comment]
Great, thanks for the fast fix
